servers:
  # 国服
  CN: &CN
    AUTH: 'https://as.hypergryph.com'
    GAME: 'https://ak-gs-gf.hypergryph.com'
    CONF: 'https://ak-conf.hypergryph.com'
    VER:  'https://ak-conf.hypergryph.com/config/prod/official/Android/version'

  # 日服
  JP: &JP
    PASSPORT: 'https://passport.arknights.jp'
    AUTH: 'https://as.arknights.jp'
    GAME: 'https://gs.arknights.jp:8443'
    CONF: 'https://ak-conf.arknights.jp'
    VER: 'https://ark-jp-static-online.yo-star.com/assetbundle/official/Android/version'
    ID: '3'

  # 美服
  US: &US
    PASSPORT: 'https://passport.arknights.global'
    AUTH: 'https://as.arknights.global'
    GAME: 'https://gs.arknights.global:8443'
    SERVER: 'https://ak-conf.arknights.global'
    VER: 'https://ark-us-static-online.yo-star.com/assetbundle/official/Android/version'
    ID: '3'

user: 
  account: '18900000000'
  password: 'edit me'
  server: *CN # 目前暂时没有实现外服功能
  platform: 'Android' # 苹果服填写 iOS

sleep: 1000
actions:
  - updateConfig
  - accountLogin
  - login
  - syncData
  - syncStatus
  - getUnconfirmedOrderIdList
  - checkIn
  - checkInActivity
  - checkMailbox
  - receiveSocialPoint
  - syncBase
  -
    condition: building_on
    then:
      - receiveResources
      - completeOrder
      - receiveIntimacy
      - syncSocialPoint
      - tradeSocialPoint
      - setAssignChar
      - getMissionRewards